name: aicore
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - earthengine-api=0.1.227
  - einops
  - efficientnet-pytorch=0.6.3
  - fsspec
  - geedim=1.7.0
  - geopandas
  - h5netcdf=1.1.0
  - joblib=1.0.1
  - matplotlib=3.2.2
  - numpy=1.18.5
  - numpy-base=1.18.5
  - opencv=4.8.1
  - pandas=1.0.5
  - pillow=9.4
  - pip=20.1.1
  - pretrainedmodels=0.7.4 
  - pyproj=2.6.1.post1
  - python=3.7
  - pytorch=1.13.1 #
  - pytorch-cuda=11.7
  - pyyaml=5.3.1
  - rasterio=1.1.5
  - requests=2.24.0
  - rioxarray=0.9.1
  - scikit-image=0.19.3
  - tensorboard=2.2.1
  - tqdm=4.65.0
  - torchvision=0.14.1 #
  - timm=0.4.12
  - wandb=0.15.3
  - xarray=2023.4.2
  - scikit-image
  - pip:
    - torchsummary=1.5.1
