name: aicore
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - albumentations=1.3
  - earthengine-api=0.1.324
  - efficientnet-pytorch=0.7.1
  - gdal=3.5.2
  - h5py=3.7.0
  - joblib=1.2.0
  - matplotlib=3.6.0
  - numpy=1.23.3
  - pandas=1.4.4
  - pip=22.2.2
  - pretrainedmodels=0.7.4
  - pyproj=3.4.0
  - python=3.10.6
  - pytorch=1.12.1
  - pyyaml=6.0
  - rasterio=1.3.2
  - requests=2.28.1
  - scikit-image=0.19.3
  - tensorboard=2.10.0
  - tqdm=4.64.1
  - torchvision=0.13.1
  - timm=0.4.12
  - pip:
    - torchsummary==1.5.1
