name: aicore
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - docopt=0.6.2
  - earthengine-api=0.1.227
  - gdal=3.0.4
  - h5py=2.10.0
  - joblib=1.0.1
  - matplotlib=3.2.2
  - numpy=1.18.5
  - numpy-base=1.18.5
  - pandas=1.0.5
  - pip=20.1.1
  - pyproj=2.6.1.post1
  - python=3.7.7
  - pytorch=1.5.1
  - pyyaml=5.3.1
  - rasterio=1.1.5
  - requests=2.24.0
  - scikit-image=0.17.2 
  - tensorboard=2.2.1
  - tqdm=4.48.0
  - torchvision=0.8.2
  - pretrainedmodels=0.7.4
  - efficientnet-pytorch=0.6.3
  - timm=0.3.2
  - pip:
    - torchsummary==1.5.1
