name: thaw_slump_segmentation
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - albumentations
  - earthengine-api
  - einops
  - efficientnet-pytorch==0.7.1
  - fsspec
  - gdal
  - geedim
  - geemap
  - geopandas
  - h5netcdf
  - h5py
  - joblib=1.3
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pip
  - pretrainedmodels
  - pyproj
  - python=3.10
  - pytorch=2.1.1
  - pytorch-cuda=11.7
  - pyyaml
  - rasterio
  - requests
  - rioxarray
  - rtree
  - scikit-image
  - tensorboard=
  - tqdm
  - torchvision
  - timm
  - wandb=0.15.3
  - xarray
  - yacs
  - pip:
    - torchsummary
