# Model Specification
model: UNet
model_args:
  output_channels: 2
  norm: BatchNorm
  stack_height: 4
# Data Configuration
data_threads: 4
data_sources:
  - planet
  - ndvi
  - tcvis
  # - relative_elevation
  # - slope
datasets:
  train:
    augment: true
    shuffle: true
    scenes:
      - "20190618_201847_1035"
      - "20190618_201848_1035"
      - "20190623_200555_0e19"
  val:
    augment: false
    shuffle: false
    scenes:
      - "20190727_160426_104e"
  test:
    augment: false
    shuffle: false
    scenes:
      - "20190709_042959_08_1057"
# Training Parameters
batch_size: 16
learning_rate: 0.001
loss_function:
  type: AutoCE
schedule:
  - phase: Training
    epochs: 30
    steps:
      - train_on: train
      - validate_on: val
      - log_images
# Visualization
visualization_tiles:
  20190727_160426_104e: [5, 52, 75, 87, 113, 139, 239, 270, 277, 291, 305]
